### ISSUE TITLE
showing error on first run

### ISSUE THREAD

**Issue by sachin-611** [Saurav-Paul/AI-virtual-assistant-python#92]
everything installed perfectly after last question "Do you want me to work fast" everything installed fine. but then this error is coming not able to resolve
`Invalid format string
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\jarvis.exe\__main__.py", line 4, in <module>
  File "c:\program files\python38\lib\site-packages\run\run.py", line 2, in <module>
    from run.main import main
  File "c:\program files\python38\lib\site-packages\run\main.py", line 11, in <module>
    from tools.AI.data import google
  File "c:\program files\python38\lib\site-packages\tools\AI\data.py", line 31, in <module>
    'what is the time' : digital_time(),
  File "c:\program files\python38\lib\site-packages\tools\AI\data.py", line 24, in digital_time
    return 'Sir now is '+time.strftime("%-I:%M %p")
ValueError: Invalid format string`

**Comment by Saurav-Paul** [comment]
Thank you for reviewing.. can you mention your operating system? I know this error can be occurred in windows terminal.. because windows terminal for some reason do not support this time format.  Can you mention your operating system?

**Comment by sachin-611** [comment]
I have dual booted ubuntu 20.04 and window 10. I tried in both same error is coming.

**Comment by Saurav-Paul** [comment]
Can you be more specific ? I used it on ubuntu.. even currently my few friends using it on ubuntu.. I am using it on Arch.. Haven't got any issue. I use it regularly.

**Comment by sachin-611** [comment]
I am using:
os name:-Ubuntu 20.04.1 LTS
os type:-64-bit
GNOME version:-3.36.3
Windowing system:-X11

**Comment by Saurav-Paul** [comment]
It should work fine brother. by the way the error you have gave here it must be from your windows.. Can you retry to install it on ubuntu? and if it don't work , then tell me the error. i will able to help.
